globals:
  onFailure:
  #  This failure handler will be called failed of any step in the pipeline
  # comment this out if you do not want to integrate pipeline with slack
  - handlerName: slack-notify-error

failureHandlers:
- name: debug-env
  image: busybox
  script: |
    echo "### PWD"
    pwd
    echo "### ENV"
    env
    echo "ls -la"
    ls -la

- name: slack-notify-error
  image: iceci/utils
  script: |
    cat <<EOF > slacknotify.json
    {
      "text" : "Build $ICECI_BUILD_NUMBER on branch $ICECI_GIT_BRANCH_NAME failed on step $ICECI_FAILED_STEP_NAME commited by $ICECI_GIT_AUTHOR_NAME"
    }
    EOF
    curl -X POST -H 'Content-type: application/json' --data "@slacknotify.json" $SLACK_WEBHOOK
  environment:
  - name: SLACK_WEBHOOK
    fromSecret: slack-webhook

# Service with postgres will run during whole pipeline
services:
- name: db
  image: postgres:11
  environment:
  - name: POSTGRES_DB
    value: testdb
  - name: POSTGRES_PASSWORD
    value: dbpass
  - name: POSTGRES_USER
    value: dbuser

steps:
- name: run-tests
  containerRun:
    image: python:3.7
    script: |
      pip install -r requirements.txt
      pip install -r requirements-test.txt
      flask initdb
      pytest quotes_tests.py
    environment:
    - name: QUOTES_DB_URI
      value: "postgresql+psycopg2://dbuser:dbpass@db:5432/testdb"
    - name: FLASK_APP
      value: quotes.py

- name: build-docker-image
  containerBuild:
    dockerSecret: dockerhub
    registry: docker.io
    # TODO: change user and image name to repository that you have access to
    user: iceci
    imageName: example-python-webapp
    tags:
    - "{{ ICECI_BUILD_NUMBER }}"
    - latest

# comment this step out if you do not want to integrate this pipeline with slack
- name: slack-notify
  containerRun:
    image: iceci/utils
    script: |
      cat <<EOF > slacknotify.json
      {
        "text" : "Build $ICECI_BUILD_NUMBER on branch $ICECI_GIT_BRANCH_NAME finished successfully!"
      }
      EOF
      curl -X POST -H 'Content-type: application/json' --data "@slacknotify.json" $SLACK_WEBHOOK
    environment:
    - name: SLACK_WEBHOOK
      fromSecret: slack-webhook
